### ISSUE TITLE
Looks great

### ISSUE THREAD

**Issue by jculverwell** [gertqin/vuex-class-modules#2]
Hi this project looks great, just wondered if before building this you saw this project https://championswimmer.in/vuex-module-decorators/ ?

If you did, may I ask how does your project differ/ what are the benefits?  Just trying to understand the differences before I select one to go with.

Thanks again

**Comment by gertqin** [comment]
Hi, I have looked at it shortly, but I don't like the way actions are handled (that you can only commit one mutation and have to specify it in the action decorator). In my projects I usually have actions with multiple commits, that's is why I created this library.

Otherwise I don't think there is much of a difference, so pick the one you prefer :).

**Comment by jculverwell** [comment]
Thank you, yeah I really like the way you don't have to specify the mutation.  I've tried the other project and it was very good but I prefer your implementation as it makes my code look cleaner.   Thanks again for this project.
